"""migracao inicial

Revision ID: 5200db494375
Revises: 
Create Date: 2024-10-25 08:05:42.358405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5200db494375'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_pizza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sabor', sa.String(length=100), nullable=True),
    sa.Column('ingredientes', sa.String(length=100), nullable=True),
    sa.Column('preco', sa.Float(precision=2, asdecimal=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_pdiddy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_pizza', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_pizza'], ['tb_pizza.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_pdiddy')
    op.drop_table('tb_usuario')
    op.drop_table('tb_pizza')
    # ### end Alembic commands ###
